services:
  db:
    image: postgres:15-alpine
    container_name: leaf-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/migrations:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leafuser -d leafapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - leaf-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leaf-backend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env.local
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/prisma:/usr/src/app/prisma
    command: >
      sh -c "bunx prisma generate &&
             bunx prisma migrate deploy &&
             bun run dev"
    networks:
      - leaf-network

  classifier:
    build:
      context: ./classifier
    container_name: leaf-classifier
    restart: unless-stopped
    ports:
      - '8000:8000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leaf-frontend
    depends_on:
      - backend
    ports:
      - '5173:80'
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - leaf-network

networks:
  leaf-network:
    driver: bridge

volumes:
  postgres_data:
