services:
  postgres:
    image: postgres:16-alpine
    container_name: lc-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leafdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: lc-backend
    depends_on:
      postgres:
        condition: service_healthy
      classifier:
        condition: service_started
    env_file:
      - ./backend/.env
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/leafdb?schema=public
      CLASSIFIER_URL: http://classifier:5000
      FRONTEND_URL: http://localhost:5173
      SESSION_SECRET: "change_me"
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads

  classifier:
    build:
      context: ./classifier
    container_name: lc-classifier
    environment:
      PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    container_name: lc-frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"

volumes:
  pgdata:
