export const baseSpecies = [
  {
    slug: "discorea-alata-l",
    commonNameEn: "Yam",
    commonNameEs: "Ñame",
    scientificName: "Discorea Alata L.",
  },
  {
    slug: "solanum-melongena",
    commonNameEn: "Eggplant",
    commonNameEs: "Berenjena",
    scientificName: "Solanum Melongena",
  },
  {
    slug: "cucumis-sativus",
    commonNameEn: "Cucumber",
    commonNameEs: "Pepino",
    scientificName: "Cucumis Sativus",
  },
  {
    slug: "zea-mays",
    commonNameEn: "Corn",
    commonNameEs: "Maíz",
    scientificName: "Zea Mays",
  },
  {
    slug: "manihot-esculenta",
    commonNameEn: "Cassava",
    commonNameEs: "Yuca",
    scientificName: "Manihot Esculenta",
  },
];

export const baseShapes = [
  { key: "acicular", nameEn: "Acicular", nameEs: "Acicular" },
  { key: "lanceolate", nameEn: "Lanceolate", nameEs: "Lanceolada" },
  { key: "orbicular", nameEn: "Orbicular", nameEs: "Orbicular" },
  { key: "rhomboid", nameEn: "Rhomboid", nameEs: "Romboide" },
  { key: "acuminate", nameEn: "Acuminate", nameEs: "Acuminada" },
  { key: "flabellate", nameEn: "Flabellate", nameEs: "Flabelada" },
  { key: "ovate", nameEn: "Ovate", nameEs: "Ovada" },
  { key: "rosette", nameEn: "Rosette", nameEs: "En roseta" },
  { key: "alternate", nameEn: "Alternate", nameEs: "Alternas" },
  { key: "hastate", nameEn: "Hastate", nameEs: "Hastada" },
  { key: "palmeate", nameEn: "Palmeate", nameEs: "Palmeada" },
  { key: "spatulate", nameEn: "Spatulate", nameEs: "Espatulada" },
  { key: "aristate", nameEn: "Aristate", nameEs: "Aristada" },
  {
    key: "simple_palmeate",
    nameEn: "Simple Palmate",
    nameEs: "Palmada simple",
  },
  { key: "sagittate", nameEn: "Sagittate", nameEs: "Sagitada" },
  { key: "bipinnate", nameEn: "Bipinnate", nameEs: "Bipinnada" },
  { key: "linear", nameEn: "Linear", nameEs: "Lineal" },
  { key: "peltate", nameEn: "Peltate", nameEs: "Peltada" },
  { key: "subulate", nameEn: "Subulate", nameEs: "Subulada" },
  { key: "cordate", nameEn: "Cordate", nameEs: "Cordada" },
  { key: "lobulate", nameEn: "Lobulate", nameEs: "Lobulada" },
  { key: "amplexicaul", nameEn: "Amplexicaul", nameEs: "Amplexicaule" },
  { key: "trifoliate", nameEn: "Trifoliate", nameEs: "Trifoliada" },
  { key: "cuneate", nameEn: "Cuneate", nameEs: "Cuneada" },
  { key: "obcordate", nameEn: "Obcordate", nameEs: "Obcordada" },
  { key: "imparipinnate", nameEn: "Imparipinnate", nameEs: "Imparipinnada" },
  { key: "tripinnate", nameEn: "Tripinnate", nameEs: "Tripinnada" },
  { key: "triangular", nameEn: "Triangular", nameEs: "Triangular" },
  { key: "obovate", nameEn: "Obovate", nameEs: "Obovada" },
  { key: "paripinnate", nameEn: "Paripinnate", nameEs: "Paripinnada" },
  { key: "truncate", nameEn: "Truncate", nameEs: "Truncada" },
  { key: "digitate", nameEn: "Digitate", nameEs: "Digitada" },
  { key: "obtuse", nameEn: "Obtuse", nameEs: "Obtusa" },
  { key: "pinnatisect", nameEn: "Pinnatisect", nameEs: "Pinnatisecta" },
  { key: "entire", nameEn: "Entire", nameEs: "Entera" },
  { key: "elliptic", nameEn: "Elliptic", nameEs: "Elíptica" },
  { key: "opposite", nameEn: "Opposite", nameEs: "Opuestas" },
  { key: "reniform", nameEn: "Reniform", nameEs: "Reniforme" },
  { key: "verticillate", nameEn: "Verticillate", nameEs: "Verticiladas" },
];
